title: canon setup || ij start canon 
description: Visit ij.start.canon for checking the printer port and setting up a Canon printer with your device. To learn how to set up, uninstall and update the Canon printer driver, go to ij.start.canon on Canon official website.
